{% set version = '4.1.4' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-statnet.common
  version: {{ version|replace("-", "_") }}

source:
  fn: statnet.common_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/statnet.common_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/statnet.common/statnet.common_{{ version }}.tar.gz
  sha256: 2cea993a52f27d8a5a5e91d3a5dcffcc86523001f6f646cd26ec37c2486dbe91

build:
  merge_build_host: True  # [win]
  number: 1000
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-coda
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-coda

test:
  commands:
    - $R -e "library('statnet.common')"           # [not win]
    - "\"%R%\" -e \"library('statnet.common')\""  # [win]

about:
  home: http://www.statnet.org
  license: GPL-3
  summary: Non-statistical utilities used by the software developed by the Statnet Project. They
    may also be of use to others.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
    - stevierene82
